10 implement community page designs
NYCEDU/nycedu-react pull request #13
Opened 2016-11-21 21:54 UTC by rickymetz

Closes #10
Closes #12

2016-11-21 21:56 UTC, rickymetz commented
Animation is not in this PR, but is captured in a separate issue ( #14 ) in order to not delay production.

2016-11-22 15:14 UTC, seanperkins requested changes
Please run those images through something to optimize them.

2016-11-22 15:14 UTC, seanperkins commented on nycedu-react.sublime-workspace
> +{
Remove this from the project.

2016-11-22 15:14 UTC, seanperkins commented on src/community/Community.js
> +        <div className="member-container">
Create a data structure to hold the community members, then .map over it to generate the markup.

2016-11-22 16:43 UTC, rickymetz commented on src/community/Community.js
> +        <div className="member-container">
Fixed in cf57398

2016-11-22 16:52 UTC, seanperkins commented on src/community/Community.js
> +        buildCommunity: "I started the Bronx Education Meetup group to help connect those involved in education in the Bronx. I’m also working on EduDAO, a blockchain educational funding project.",
Build Community: I am working to ensure the technology we create for NYCEDU stays open and maintainable by the community. I also like to help folks that are new to software development get started in the field.

2016-11-22 16:55 UTC, seanperkins commented on src/community/Community.js
> +        getInvolved: <p>Sign up for the meetup or email me at eugene.leventhal@gmail.com.</p>
```
<p>Check out the #NYCEDU <a target="_blank" href="https://github.com/NYCEDU/">Github repo</a> to see what's being created by our community. Interact with others in the <a target="_blank" href="https://nycedu.slack.com/messages/we_are_developers/">#we_are_developers</a> channel in Slack.
```

2016-11-23 14:17 UTC, seanperkins approved these changes

2016-11-23 14:18 UTC, merged